[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/api/status"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"

# Resource optimization for Railway stability
startCommand = "python server.py"
numReplicas = 1

# Environment variables for Railway optimization
[deploy.environmentVariables]
PYTHONOPTIMIZE = "1"
PYTHONDONTWRITEBYTECODE = "1"
PYTHONUNBUFFERED = "1"
RAILWAY_STATIC_URL = "/"
RAILWAY_PUBLIC_DOMAIN = "true"